            </main>
            <footer>
                <nav id="navbarBas" class="navbar navbar-expand-md bg-dark navbar-dark">
                    <!-- bouton burger -->
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#burgerBas">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Contenu du menu -->
                    <div id="burgerBas" class="navbar navbar-expand-md bg-dark navbar-dark">
                        <ul class="navbar-nav">    
                            <li class="nav-item menuspc"><a href="legal.html" class="text-white">Mention&nbsp;légales</a></li>
                            <li class="nav-item menuspc"><a href="horaires.html" class="text-white">Horaires</a></li>
                            <li class="nav-item menuspc"><a href="plan.html" class="text-white">Plan&nbsp;du&nbsp;site</a></li>
                        </ul>
                    </div>
                </nav>
            </footer>
            <script src="assets/js/jquery-3.3.1.slim.min.js"></script>
            <script src="assets/js/popper.1.14.7.min.js"></script>
            <script src="assets/js/bootstrap/bootstrap.min.js"></script>
        </body>
    </html>